// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.opentivi

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_opentivi_android_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_opentivi_android_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "uniffi_opentivi"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}








































































































// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            loadIndirect<UniffiLib>(componentName = "opentivi")
            .also { lib: UniffiLib ->
                uniffiCheckContractApiVersion(lib)
                uniffiCheckApiChecksums(lib)
                }
        }
        
    }

    fun uniffi_opentivi_android_fn_func_delete_source(`sourceId`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_opentivi_android_fn_func_get_all_settings(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_opentivi_android_fn_func_get_channel(`channelId`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_opentivi_android_fn_func_get_channel_epg(`channelId`: Long,`fromTs`: RustBuffer.ByValue,`toTs`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_opentivi_android_fn_func_get_channels_epg_snapshots(`channelIds`: RustBuffer.ByValue,`windowStartTs`: RustBuffer.ByValue,`windowEndTs`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_opentivi_android_fn_func_get_proxy_port(uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun uniffi_opentivi_android_fn_func_import_m3u(`name`: RustBuffer.ByValue,`location`: RustBuffer.ByValue,`autoRefreshMinutes`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_opentivi_android_fn_func_import_xmltv(`name`: RustBuffer.ByValue,`location`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_opentivi_android_fn_func_import_xtream(`name`: RustBuffer.ByValue,`serverUrl`: RustBuffer.ByValue,`username`: RustBuffer.ByValue,`password`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_opentivi_android_fn_func_init_engine(`dataDir`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun uniffi_opentivi_android_fn_func_list_channels(`sourceId`: RustBuffer.ByValue,`groupName`: RustBuffer.ByValue,`search`: RustBuffer.ByValue,`favoritesOnly`: RustBuffer.ByValue,`limit`: Int,`offset`: Int,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_opentivi_android_fn_func_list_favorites(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_opentivi_android_fn_func_list_groups(`sourceId`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_opentivi_android_fn_func_list_playback_candidates(`channelId`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_opentivi_android_fn_func_list_recents(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_opentivi_android_fn_func_list_sources(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_opentivi_android_fn_func_mark_recent_watched(`channelId`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_opentivi_android_fn_func_refresh_source(`sourceId`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_opentivi_android_fn_func_resolve_playback(`channelId`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_opentivi_android_fn_func_search_epg(`search`: RustBuffer.ByValue,`state`: RustBuffer.ByValue,`limit`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun uniffi_opentivi_android_fn_func_set_favorite(`channelId`: Long,`favorite`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_opentivi_android_fn_func_set_setting(`key`: RustBuffer.ByValue,`value`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_opentivi_android_fn_func_update_source(`sourceId`: Long,`name`: RustBuffer.ByValue,`location`: RustBuffer.ByValue,`username`: RustBuffer.ByValue,`password`: RustBuffer.ByValue,`autoRefreshMinutes`: RustBuffer.ByValue,`enabled`: Byte,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_opentivi_android_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_opentivi_android_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_opentivi_android_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun ffi_opentivi_android_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_opentivi_android_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_free_u8(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_opentivi_android_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_free_i8(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    fun ffi_opentivi_android_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_free_u16(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_opentivi_android_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_free_i16(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    fun ffi_opentivi_android_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_free_u32(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_opentivi_android_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_free_i32(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    fun ffi_opentivi_android_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_free_u64(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_opentivi_android_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_free_i64(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    fun ffi_opentivi_android_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_free_f32(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    fun ffi_opentivi_android_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_free_f64(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    fun ffi_opentivi_android_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_cancel_pointer(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_free_pointer(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Pointer
    fun ffi_opentivi_android_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    fun ffi_opentivi_android_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_cancel_void(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_free_void(`handle`: Long,
    ): Unit
    fun ffi_opentivi_android_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    fun uniffi_opentivi_android_checksum_func_delete_source(
    ): Short
    fun uniffi_opentivi_android_checksum_func_get_all_settings(
    ): Short
    fun uniffi_opentivi_android_checksum_func_get_channel(
    ): Short
    fun uniffi_opentivi_android_checksum_func_get_channel_epg(
    ): Short
    fun uniffi_opentivi_android_checksum_func_get_channels_epg_snapshots(
    ): Short
    fun uniffi_opentivi_android_checksum_func_get_proxy_port(
    ): Short
    fun uniffi_opentivi_android_checksum_func_import_m3u(
    ): Short
    fun uniffi_opentivi_android_checksum_func_import_xmltv(
    ): Short
    fun uniffi_opentivi_android_checksum_func_import_xtream(
    ): Short
    fun uniffi_opentivi_android_checksum_func_init_engine(
    ): Short
    fun uniffi_opentivi_android_checksum_func_list_channels(
    ): Short
    fun uniffi_opentivi_android_checksum_func_list_favorites(
    ): Short
    fun uniffi_opentivi_android_checksum_func_list_groups(
    ): Short
    fun uniffi_opentivi_android_checksum_func_list_playback_candidates(
    ): Short
    fun uniffi_opentivi_android_checksum_func_list_recents(
    ): Short
    fun uniffi_opentivi_android_checksum_func_list_sources(
    ): Short
    fun uniffi_opentivi_android_checksum_func_mark_recent_watched(
    ): Short
    fun uniffi_opentivi_android_checksum_func_refresh_source(
    ): Short
    fun uniffi_opentivi_android_checksum_func_resolve_playback(
    ): Short
    fun uniffi_opentivi_android_checksum_func_search_epg(
    ): Short
    fun uniffi_opentivi_android_checksum_func_set_favorite(
    ): Short
    fun uniffi_opentivi_android_checksum_func_set_setting(
    ): Short
    fun uniffi_opentivi_android_checksum_func_update_source(
    ): Short
    fun ffi_opentivi_android_uniffi_contract_version(
    ): Int
    
}

private fun uniffiCheckContractApiVersion(lib: UniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_opentivi_android_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}

@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: UniffiLib) {
    if (lib.uniffi_opentivi_android_checksum_func_delete_source() != 29563.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_get_all_settings() != 54609.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_get_channel() != 3302.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_get_channel_epg() != 23229.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_get_channels_epg_snapshots() != 5067.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_get_proxy_port() != 38720.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_import_m3u() != 17176.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_import_xmltv() != 26118.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_import_xtream() != 42847.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_init_engine() != 52146.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_list_channels() != 50759.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_list_favorites() != 39427.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_list_groups() != 39749.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_list_playback_candidates() != 57399.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_list_recents() != 5624.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_list_sources() != 59387.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_mark_recent_watched() != 168.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_refresh_source() != 30577.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_resolve_playback() != 45741.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_search_epg() != 34089.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_set_favorite() != 42842.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_set_setting() != 8492.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_opentivi_android_checksum_func_update_source() != 34965.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            args.filterIsInstance<Disposable>()
                .forEach(Disposable::destroy)
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer

/**
 * @suppress
 */
public object FfiConverterUShort: FfiConverter<UShort, Short> {
    override fun lift(value: Short): UShort {
        return value.toUShort()
    }

    override fun read(buf: ByteBuffer): UShort {
        return lift(buf.getShort())
    }

    override fun lower(value: UShort): Short {
        return value.toShort()
    }

    override fun allocationSize(value: UShort) = 2UL

    override fun write(value: UShort, buf: ByteBuffer) {
        buf.putShort(value.toShort())
    }
}

/**
 * @suppress
 */
public object FfiConverterUInt: FfiConverter<UInt, Int> {
    override fun lift(value: Int): UInt {
        return value.toUInt()
    }

    override fun read(buf: ByteBuffer): UInt {
        return lift(buf.getInt())
    }

    override fun lower(value: UInt): Int {
        return value.toInt()
    }

    override fun allocationSize(value: UInt) = 4UL

    override fun write(value: UInt, buf: ByteBuffer) {
        buf.putInt(value.toInt())
    }
}

/**
 * @suppress
 */
public object FfiConverterLong: FfiConverter<Long, Long> {
    override fun lift(value: Long): Long {
        return value
    }

    override fun read(buf: ByteBuffer): Long {
        return buf.getLong()
    }

    override fun lower(value: Long): Long {
        return value
    }

    override fun allocationSize(value: Long) = 8UL

    override fun write(value: Long, buf: ByteBuffer) {
        buf.putLong(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}



data class ChannelEpgSnapshot (
    var `channelId`: kotlin.Long, 
    var `now`: EpgProgramMini?, 
    var `next`: EpgProgramMini?, 
    var `timelinePrograms`: List<EpgProgramMini>
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeChannelEpgSnapshot: FfiConverterRustBuffer<ChannelEpgSnapshot> {
    override fun read(buf: ByteBuffer): ChannelEpgSnapshot {
        return ChannelEpgSnapshot(
            FfiConverterLong.read(buf),
            FfiConverterOptionalTypeEpgProgramMini.read(buf),
            FfiConverterOptionalTypeEpgProgramMini.read(buf),
            FfiConverterSequenceTypeEpgProgramMini.read(buf),
        )
    }

    override fun allocationSize(value: ChannelEpgSnapshot) = (
            FfiConverterLong.allocationSize(value.`channelId`) +
            FfiConverterOptionalTypeEpgProgramMini.allocationSize(value.`now`) +
            FfiConverterOptionalTypeEpgProgramMini.allocationSize(value.`next`) +
            FfiConverterSequenceTypeEpgProgramMini.allocationSize(value.`timelinePrograms`)
    )

    override fun write(value: ChannelEpgSnapshot, buf: ByteBuffer) {
            FfiConverterLong.write(value.`channelId`, buf)
            FfiConverterOptionalTypeEpgProgramMini.write(value.`now`, buf)
            FfiConverterOptionalTypeEpgProgramMini.write(value.`next`, buf)
            FfiConverterSequenceTypeEpgProgramMini.write(value.`timelinePrograms`, buf)
    }
}



data class ChannelInfo (
    var `id`: kotlin.Long, 
    var `sourceId`: kotlin.Long, 
    var `name`: kotlin.String, 
    var `channelNumber`: kotlin.String?, 
    var `groupName`: kotlin.String?, 
    var `tvgId`: kotlin.String?, 
    var `logoUrl`: kotlin.String?, 
    var `streamUrl`: kotlin.String, 
    var `isFavorite`: kotlin.Boolean
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeChannelInfo: FfiConverterRustBuffer<ChannelInfo> {
    override fun read(buf: ByteBuffer): ChannelInfo {
        return ChannelInfo(
            FfiConverterLong.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: ChannelInfo) = (
            FfiConverterLong.allocationSize(value.`id`) +
            FfiConverterLong.allocationSize(value.`sourceId`) +
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterOptionalString.allocationSize(value.`channelNumber`) +
            FfiConverterOptionalString.allocationSize(value.`groupName`) +
            FfiConverterOptionalString.allocationSize(value.`tvgId`) +
            FfiConverterOptionalString.allocationSize(value.`logoUrl`) +
            FfiConverterString.allocationSize(value.`streamUrl`) +
            FfiConverterBoolean.allocationSize(value.`isFavorite`)
    )

    override fun write(value: ChannelInfo, buf: ByteBuffer) {
            FfiConverterLong.write(value.`id`, buf)
            FfiConverterLong.write(value.`sourceId`, buf)
            FfiConverterString.write(value.`name`, buf)
            FfiConverterOptionalString.write(value.`channelNumber`, buf)
            FfiConverterOptionalString.write(value.`groupName`, buf)
            FfiConverterOptionalString.write(value.`tvgId`, buf)
            FfiConverterOptionalString.write(value.`logoUrl`, buf)
            FfiConverterString.write(value.`streamUrl`, buf)
            FfiConverterBoolean.write(value.`isFavorite`, buf)
    }
}



data class EpgProgramInfo (
    var `id`: kotlin.Long, 
    var `channelTvgId`: kotlin.String, 
    var `startAt`: kotlin.String, 
    var `endAt`: kotlin.String, 
    var `title`: kotlin.String, 
    var `description`: kotlin.String?, 
    var `category`: kotlin.String?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeEpgProgramInfo: FfiConverterRustBuffer<EpgProgramInfo> {
    override fun read(buf: ByteBuffer): EpgProgramInfo {
        return EpgProgramInfo(
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: EpgProgramInfo) = (
            FfiConverterLong.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`channelTvgId`) +
            FfiConverterString.allocationSize(value.`startAt`) +
            FfiConverterString.allocationSize(value.`endAt`) +
            FfiConverterString.allocationSize(value.`title`) +
            FfiConverterOptionalString.allocationSize(value.`description`) +
            FfiConverterOptionalString.allocationSize(value.`category`)
    )

    override fun write(value: EpgProgramInfo, buf: ByteBuffer) {
            FfiConverterLong.write(value.`id`, buf)
            FfiConverterString.write(value.`channelTvgId`, buf)
            FfiConverterString.write(value.`startAt`, buf)
            FfiConverterString.write(value.`endAt`, buf)
            FfiConverterString.write(value.`title`, buf)
            FfiConverterOptionalString.write(value.`description`, buf)
            FfiConverterOptionalString.write(value.`category`, buf)
    }
}



data class EpgProgramMini (
    var `title`: kotlin.String, 
    var `startAt`: kotlin.String, 
    var `endAt`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeEpgProgramMini: FfiConverterRustBuffer<EpgProgramMini> {
    override fun read(buf: ByteBuffer): EpgProgramMini {
        return EpgProgramMini(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: EpgProgramMini) = (
            FfiConverterString.allocationSize(value.`title`) +
            FfiConverterString.allocationSize(value.`startAt`) +
            FfiConverterString.allocationSize(value.`endAt`)
    )

    override fun write(value: EpgProgramMini, buf: ByteBuffer) {
            FfiConverterString.write(value.`title`, buf)
            FfiConverterString.write(value.`startAt`, buf)
            FfiConverterString.write(value.`endAt`, buf)
    }
}



data class EpgSearchResult (
    var `id`: kotlin.Long, 
    var `channelId`: kotlin.Long, 
    var `sourceId`: kotlin.Long, 
    var `channelName`: kotlin.String, 
    var `channelNumber`: kotlin.String?, 
    var `channelTvgId`: kotlin.String, 
    var `startAt`: kotlin.String, 
    var `endAt`: kotlin.String, 
    var `title`: kotlin.String, 
    var `description`: kotlin.String?, 
    var `category`: kotlin.String?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeEpgSearchResult: FfiConverterRustBuffer<EpgSearchResult> {
    override fun read(buf: ByteBuffer): EpgSearchResult {
        return EpgSearchResult(
            FfiConverterLong.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: EpgSearchResult) = (
            FfiConverterLong.allocationSize(value.`id`) +
            FfiConverterLong.allocationSize(value.`channelId`) +
            FfiConverterLong.allocationSize(value.`sourceId`) +
            FfiConverterString.allocationSize(value.`channelName`) +
            FfiConverterOptionalString.allocationSize(value.`channelNumber`) +
            FfiConverterString.allocationSize(value.`channelTvgId`) +
            FfiConverterString.allocationSize(value.`startAt`) +
            FfiConverterString.allocationSize(value.`endAt`) +
            FfiConverterString.allocationSize(value.`title`) +
            FfiConverterOptionalString.allocationSize(value.`description`) +
            FfiConverterOptionalString.allocationSize(value.`category`)
    )

    override fun write(value: EpgSearchResult, buf: ByteBuffer) {
            FfiConverterLong.write(value.`id`, buf)
            FfiConverterLong.write(value.`channelId`, buf)
            FfiConverterLong.write(value.`sourceId`, buf)
            FfiConverterString.write(value.`channelName`, buf)
            FfiConverterOptionalString.write(value.`channelNumber`, buf)
            FfiConverterString.write(value.`channelTvgId`, buf)
            FfiConverterString.write(value.`startAt`, buf)
            FfiConverterString.write(value.`endAt`, buf)
            FfiConverterString.write(value.`title`, buf)
            FfiConverterOptionalString.write(value.`description`, buf)
            FfiConverterOptionalString.write(value.`category`, buf)
    }
}



data class ImportResult (
    var `sourceId`: kotlin.Long, 
    var `channelsImported`: kotlin.UInt, 
    var `channelsUpdated`: kotlin.UInt, 
    var `channelsRemoved`: kotlin.UInt
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeImportResult: FfiConverterRustBuffer<ImportResult> {
    override fun read(buf: ByteBuffer): ImportResult {
        return ImportResult(
            FfiConverterLong.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
        )
    }

    override fun allocationSize(value: ImportResult) = (
            FfiConverterLong.allocationSize(value.`sourceId`) +
            FfiConverterUInt.allocationSize(value.`channelsImported`) +
            FfiConverterUInt.allocationSize(value.`channelsUpdated`) +
            FfiConverterUInt.allocationSize(value.`channelsRemoved`)
    )

    override fun write(value: ImportResult, buf: ByteBuffer) {
            FfiConverterLong.write(value.`sourceId`, buf)
            FfiConverterUInt.write(value.`channelsImported`, buf)
            FfiConverterUInt.write(value.`channelsUpdated`, buf)
            FfiConverterUInt.write(value.`channelsRemoved`, buf)
    }
}



data class PlaybackInfo (
    var `channelId`: kotlin.Long, 
    var `resolvedChannelId`: kotlin.Long, 
    var `sourceId`: kotlin.Long, 
    var `channelName`: kotlin.String, 
    var `streamUrl`: kotlin.String, 
    var `logoUrl`: kotlin.String?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePlaybackInfo: FfiConverterRustBuffer<PlaybackInfo> {
    override fun read(buf: ByteBuffer): PlaybackInfo {
        return PlaybackInfo(
            FfiConverterLong.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: PlaybackInfo) = (
            FfiConverterLong.allocationSize(value.`channelId`) +
            FfiConverterLong.allocationSize(value.`resolvedChannelId`) +
            FfiConverterLong.allocationSize(value.`sourceId`) +
            FfiConverterString.allocationSize(value.`channelName`) +
            FfiConverterString.allocationSize(value.`streamUrl`) +
            FfiConverterOptionalString.allocationSize(value.`logoUrl`)
    )

    override fun write(value: PlaybackInfo, buf: ByteBuffer) {
            FfiConverterLong.write(value.`channelId`, buf)
            FfiConverterLong.write(value.`resolvedChannelId`, buf)
            FfiConverterLong.write(value.`sourceId`, buf)
            FfiConverterString.write(value.`channelName`, buf)
            FfiConverterString.write(value.`streamUrl`, buf)
            FfiConverterOptionalString.write(value.`logoUrl`, buf)
    }
}



data class RecentChannelInfo (
    var `id`: kotlin.Long, 
    var `sourceId`: kotlin.Long, 
    var `name`: kotlin.String, 
    var `channelNumber`: kotlin.String?, 
    var `groupName`: kotlin.String?, 
    var `tvgId`: kotlin.String?, 
    var `logoUrl`: kotlin.String?, 
    var `streamUrl`: kotlin.String, 
    var `isFavorite`: kotlin.Boolean, 
    var `lastWatchedAt`: kotlin.String, 
    var `playCount`: kotlin.Long
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeRecentChannelInfo: FfiConverterRustBuffer<RecentChannelInfo> {
    override fun read(buf: ByteBuffer): RecentChannelInfo {
        return RecentChannelInfo(
            FfiConverterLong.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterString.read(buf),
            FfiConverterLong.read(buf),
        )
    }

    override fun allocationSize(value: RecentChannelInfo) = (
            FfiConverterLong.allocationSize(value.`id`) +
            FfiConverterLong.allocationSize(value.`sourceId`) +
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterOptionalString.allocationSize(value.`channelNumber`) +
            FfiConverterOptionalString.allocationSize(value.`groupName`) +
            FfiConverterOptionalString.allocationSize(value.`tvgId`) +
            FfiConverterOptionalString.allocationSize(value.`logoUrl`) +
            FfiConverterString.allocationSize(value.`streamUrl`) +
            FfiConverterBoolean.allocationSize(value.`isFavorite`) +
            FfiConverterString.allocationSize(value.`lastWatchedAt`) +
            FfiConverterLong.allocationSize(value.`playCount`)
    )

    override fun write(value: RecentChannelInfo, buf: ByteBuffer) {
            FfiConverterLong.write(value.`id`, buf)
            FfiConverterLong.write(value.`sourceId`, buf)
            FfiConverterString.write(value.`name`, buf)
            FfiConverterOptionalString.write(value.`channelNumber`, buf)
            FfiConverterOptionalString.write(value.`groupName`, buf)
            FfiConverterOptionalString.write(value.`tvgId`, buf)
            FfiConverterOptionalString.write(value.`logoUrl`, buf)
            FfiConverterString.write(value.`streamUrl`, buf)
            FfiConverterBoolean.write(value.`isFavorite`, buf)
            FfiConverterString.write(value.`lastWatchedAt`, buf)
            FfiConverterLong.write(value.`playCount`, buf)
    }
}



data class SettingInfo (
    var `key`: kotlin.String, 
    var `value`: kotlin.String, 
    var `updatedAt`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSettingInfo: FfiConverterRustBuffer<SettingInfo> {
    override fun read(buf: ByteBuffer): SettingInfo {
        return SettingInfo(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: SettingInfo) = (
            FfiConverterString.allocationSize(value.`key`) +
            FfiConverterString.allocationSize(value.`value`) +
            FfiConverterString.allocationSize(value.`updatedAt`)
    )

    override fun write(value: SettingInfo, buf: ByteBuffer) {
            FfiConverterString.write(value.`key`, buf)
            FfiConverterString.write(value.`value`, buf)
            FfiConverterString.write(value.`updatedAt`, buf)
    }
}



data class SourceInfo (
    var `id`: kotlin.Long, 
    var `kind`: kotlin.String, 
    var `name`: kotlin.String, 
    var `location`: kotlin.String, 
    var `username`: kotlin.String?, 
    var `password`: kotlin.String?, 
    var `enabled`: kotlin.Boolean, 
    var `disabledReason`: kotlin.String?, 
    var `autoRefreshMinutes`: kotlin.UInt?, 
    var `channelCount`: kotlin.UInt, 
    var `groupCount`: kotlin.UInt, 
    var `channelsWithTvgId`: kotlin.UInt, 
    var `epgProgramCount`: kotlin.UInt, 
    var `lastImportedAt`: kotlin.String?, 
    var `lastRefreshError`: kotlin.String?, 
    var `lastRefreshAttemptAt`: kotlin.String?, 
    var `consecutiveRefreshFailures`: kotlin.UInt, 
    var `nextRetryAt`: kotlin.String?, 
    var `createdAt`: kotlin.String, 
    var `updatedAt`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeSourceInfo: FfiConverterRustBuffer<SourceInfo> {
    override fun read(buf: ByteBuffer): SourceInfo {
        return SourceInfo(
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterBoolean.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterUInt.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: SourceInfo) = (
            FfiConverterLong.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`kind`) +
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterString.allocationSize(value.`location`) +
            FfiConverterOptionalString.allocationSize(value.`username`) +
            FfiConverterOptionalString.allocationSize(value.`password`) +
            FfiConverterBoolean.allocationSize(value.`enabled`) +
            FfiConverterOptionalString.allocationSize(value.`disabledReason`) +
            FfiConverterOptionalUInt.allocationSize(value.`autoRefreshMinutes`) +
            FfiConverterUInt.allocationSize(value.`channelCount`) +
            FfiConverterUInt.allocationSize(value.`groupCount`) +
            FfiConverterUInt.allocationSize(value.`channelsWithTvgId`) +
            FfiConverterUInt.allocationSize(value.`epgProgramCount`) +
            FfiConverterOptionalString.allocationSize(value.`lastImportedAt`) +
            FfiConverterOptionalString.allocationSize(value.`lastRefreshError`) +
            FfiConverterOptionalString.allocationSize(value.`lastRefreshAttemptAt`) +
            FfiConverterUInt.allocationSize(value.`consecutiveRefreshFailures`) +
            FfiConverterOptionalString.allocationSize(value.`nextRetryAt`) +
            FfiConverterString.allocationSize(value.`createdAt`) +
            FfiConverterString.allocationSize(value.`updatedAt`)
    )

    override fun write(value: SourceInfo, buf: ByteBuffer) {
            FfiConverterLong.write(value.`id`, buf)
            FfiConverterString.write(value.`kind`, buf)
            FfiConverterString.write(value.`name`, buf)
            FfiConverterString.write(value.`location`, buf)
            FfiConverterOptionalString.write(value.`username`, buf)
            FfiConverterOptionalString.write(value.`password`, buf)
            FfiConverterBoolean.write(value.`enabled`, buf)
            FfiConverterOptionalString.write(value.`disabledReason`, buf)
            FfiConverterOptionalUInt.write(value.`autoRefreshMinutes`, buf)
            FfiConverterUInt.write(value.`channelCount`, buf)
            FfiConverterUInt.write(value.`groupCount`, buf)
            FfiConverterUInt.write(value.`channelsWithTvgId`, buf)
            FfiConverterUInt.write(value.`epgProgramCount`, buf)
            FfiConverterOptionalString.write(value.`lastImportedAt`, buf)
            FfiConverterOptionalString.write(value.`lastRefreshError`, buf)
            FfiConverterOptionalString.write(value.`lastRefreshAttemptAt`, buf)
            FfiConverterUInt.write(value.`consecutiveRefreshFailures`, buf)
            FfiConverterOptionalString.write(value.`nextRetryAt`, buf)
            FfiConverterString.write(value.`createdAt`, buf)
            FfiConverterString.write(value.`updatedAt`, buf)
    }
}





sealed class OpenTiviException(message: String): kotlin.Exception(message) {
        
        class Runtime(message: String) : OpenTiviException(message)
        

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<OpenTiviException> {
        override fun lift(error_buf: RustBuffer.ByValue): OpenTiviException = FfiConverterTypeOpenTiviError.lift(error_buf)
    }
}

/**
 * @suppress
 */
public object FfiConverterTypeOpenTiviError : FfiConverterRustBuffer<OpenTiviException> {
    override fun read(buf: ByteBuffer): OpenTiviException {
        
            return when(buf.getInt()) {
            1 -> OpenTiviException.Runtime(FfiConverterString.read(buf))
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
        
    }

    override fun allocationSize(value: OpenTiviException): ULong {
        return 4UL
    }

    override fun write(value: OpenTiviException, buf: ByteBuffer) {
        when(value) {
            is OpenTiviException.Runtime -> {
                buf.putInt(1)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterOptionalUInt: FfiConverterRustBuffer<kotlin.UInt?> {
    override fun read(buf: ByteBuffer): kotlin.UInt? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterUInt.read(buf)
    }

    override fun allocationSize(value: kotlin.UInt?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterUInt.allocationSize(value)
        }
    }

    override fun write(value: kotlin.UInt?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterUInt.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalLong: FfiConverterRustBuffer<kotlin.Long?> {
    override fun read(buf: ByteBuffer): kotlin.Long? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterLong.read(buf)
    }

    override fun allocationSize(value: kotlin.Long?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterLong.allocationSize(value)
        }
    }

    override fun write(value: kotlin.Long?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterLong.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalBoolean: FfiConverterRustBuffer<kotlin.Boolean?> {
    override fun read(buf: ByteBuffer): kotlin.Boolean? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterBoolean.read(buf)
    }

    override fun allocationSize(value: kotlin.Boolean?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterBoolean.allocationSize(value)
        }
    }

    override fun write(value: kotlin.Boolean?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterBoolean.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeChannelInfo: FfiConverterRustBuffer<ChannelInfo?> {
    override fun read(buf: ByteBuffer): ChannelInfo? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeChannelInfo.read(buf)
    }

    override fun allocationSize(value: ChannelInfo?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeChannelInfo.allocationSize(value)
        }
    }

    override fun write(value: ChannelInfo?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeChannelInfo.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeEpgProgramMini: FfiConverterRustBuffer<EpgProgramMini?> {
    override fun read(buf: ByteBuffer): EpgProgramMini? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeEpgProgramMini.read(buf)
    }

    override fun allocationSize(value: EpgProgramMini?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeEpgProgramMini.allocationSize(value)
        }
    }

    override fun write(value: EpgProgramMini?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeEpgProgramMini.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceLong: FfiConverterRustBuffer<List<kotlin.Long>> {
    override fun read(buf: ByteBuffer): List<kotlin.Long> {
        val len = buf.getInt()
        return List<kotlin.Long>(len) {
            FfiConverterLong.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.Long>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterLong.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.Long>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterLong.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeChannelEpgSnapshot: FfiConverterRustBuffer<List<ChannelEpgSnapshot>> {
    override fun read(buf: ByteBuffer): List<ChannelEpgSnapshot> {
        val len = buf.getInt()
        return List<ChannelEpgSnapshot>(len) {
            FfiConverterTypeChannelEpgSnapshot.read(buf)
        }
    }

    override fun allocationSize(value: List<ChannelEpgSnapshot>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeChannelEpgSnapshot.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<ChannelEpgSnapshot>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeChannelEpgSnapshot.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeChannelInfo: FfiConverterRustBuffer<List<ChannelInfo>> {
    override fun read(buf: ByteBuffer): List<ChannelInfo> {
        val len = buf.getInt()
        return List<ChannelInfo>(len) {
            FfiConverterTypeChannelInfo.read(buf)
        }
    }

    override fun allocationSize(value: List<ChannelInfo>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeChannelInfo.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<ChannelInfo>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeChannelInfo.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeEpgProgramInfo: FfiConverterRustBuffer<List<EpgProgramInfo>> {
    override fun read(buf: ByteBuffer): List<EpgProgramInfo> {
        val len = buf.getInt()
        return List<EpgProgramInfo>(len) {
            FfiConverterTypeEpgProgramInfo.read(buf)
        }
    }

    override fun allocationSize(value: List<EpgProgramInfo>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeEpgProgramInfo.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<EpgProgramInfo>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeEpgProgramInfo.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeEpgProgramMini: FfiConverterRustBuffer<List<EpgProgramMini>> {
    override fun read(buf: ByteBuffer): List<EpgProgramMini> {
        val len = buf.getInt()
        return List<EpgProgramMini>(len) {
            FfiConverterTypeEpgProgramMini.read(buf)
        }
    }

    override fun allocationSize(value: List<EpgProgramMini>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeEpgProgramMini.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<EpgProgramMini>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeEpgProgramMini.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeEpgSearchResult: FfiConverterRustBuffer<List<EpgSearchResult>> {
    override fun read(buf: ByteBuffer): List<EpgSearchResult> {
        val len = buf.getInt()
        return List<EpgSearchResult>(len) {
            FfiConverterTypeEpgSearchResult.read(buf)
        }
    }

    override fun allocationSize(value: List<EpgSearchResult>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeEpgSearchResult.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<EpgSearchResult>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeEpgSearchResult.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypePlaybackInfo: FfiConverterRustBuffer<List<PlaybackInfo>> {
    override fun read(buf: ByteBuffer): List<PlaybackInfo> {
        val len = buf.getInt()
        return List<PlaybackInfo>(len) {
            FfiConverterTypePlaybackInfo.read(buf)
        }
    }

    override fun allocationSize(value: List<PlaybackInfo>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypePlaybackInfo.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<PlaybackInfo>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypePlaybackInfo.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeRecentChannelInfo: FfiConverterRustBuffer<List<RecentChannelInfo>> {
    override fun read(buf: ByteBuffer): List<RecentChannelInfo> {
        val len = buf.getInt()
        return List<RecentChannelInfo>(len) {
            FfiConverterTypeRecentChannelInfo.read(buf)
        }
    }

    override fun allocationSize(value: List<RecentChannelInfo>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeRecentChannelInfo.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<RecentChannelInfo>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeRecentChannelInfo.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeSettingInfo: FfiConverterRustBuffer<List<SettingInfo>> {
    override fun read(buf: ByteBuffer): List<SettingInfo> {
        val len = buf.getInt()
        return List<SettingInfo>(len) {
            FfiConverterTypeSettingInfo.read(buf)
        }
    }

    override fun allocationSize(value: List<SettingInfo>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeSettingInfo.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<SettingInfo>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeSettingInfo.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeSourceInfo: FfiConverterRustBuffer<List<SourceInfo>> {
    override fun read(buf: ByteBuffer): List<SourceInfo> {
        val len = buf.getInt()
        return List<SourceInfo>(len) {
            FfiConverterTypeSourceInfo.read(buf)
        }
    }

    override fun allocationSize(value: List<SourceInfo>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeSourceInfo.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<SourceInfo>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeSourceInfo.write(it, buf)
        }
    }
}

/**
 * UniFFI namespace `opentivi` — API surface for the Rust engine.
 */
public object Opentivi {
    @Throws(OpenTiviException::class) fun `deleteSource`(`sourceId`: kotlin.Long)
        = 
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_delete_source(
        FfiConverterLong.lower(`sourceId`),_status)
}
    
    

    @Throws(OpenTiviException::class) fun `getAllSettings`(): List<SettingInfo> {
            return FfiConverterSequenceTypeSettingInfo.lift(
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_get_all_settings(
        _status)
}
    )
    }
    

    @Throws(OpenTiviException::class) fun `getChannel`(`channelId`: kotlin.Long): ChannelInfo? {
            return FfiConverterOptionalTypeChannelInfo.lift(
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_get_channel(
        FfiConverterLong.lower(`channelId`),_status)
}
    )
    }
    

    @Throws(OpenTiviException::class) fun `getChannelEpg`(`channelId`: kotlin.Long, `fromTs`: kotlin.String?, `toTs`: kotlin.String?): List<EpgProgramInfo> {
            return FfiConverterSequenceTypeEpgProgramInfo.lift(
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_get_channel_epg(
        FfiConverterLong.lower(`channelId`),FfiConverterOptionalString.lower(`fromTs`),FfiConverterOptionalString.lower(`toTs`),_status)
}
    )
    }
    

    @Throws(OpenTiviException::class) fun `getChannelsEpgSnapshots`(`channelIds`: List<kotlin.Long>, `windowStartTs`: kotlin.Long?, `windowEndTs`: kotlin.Long?): List<ChannelEpgSnapshot> {
            return FfiConverterSequenceTypeChannelEpgSnapshot.lift(
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_get_channels_epg_snapshots(
        FfiConverterSequenceLong.lower(`channelIds`),FfiConverterOptionalLong.lower(`windowStartTs`),FfiConverterOptionalLong.lower(`windowEndTs`),_status)
}
    )
    }
    

    @Throws(OpenTiviException::class) fun `getProxyPort`(): kotlin.UShort {
            return FfiConverterUShort.lift(
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_get_proxy_port(
        _status)
}
    )
    }
    

    @Throws(OpenTiviException::class) fun `importM3u`(`name`: kotlin.String, `location`: kotlin.String, `autoRefreshMinutes`: kotlin.UInt?): ImportResult {
            return FfiConverterTypeImportResult.lift(
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_import_m3u(
        FfiConverterString.lower(`name`),FfiConverterString.lower(`location`),FfiConverterOptionalUInt.lower(`autoRefreshMinutes`),_status)
}
    )
    }
    

    @Throws(OpenTiviException::class) fun `importXmltv`(`name`: kotlin.String, `location`: kotlin.String): ImportResult {
            return FfiConverterTypeImportResult.lift(
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_import_xmltv(
        FfiConverterString.lower(`name`),FfiConverterString.lower(`location`),_status)
}
    )
    }
    

    @Throws(OpenTiviException::class) fun `importXtream`(`name`: kotlin.String, `serverUrl`: kotlin.String, `username`: kotlin.String, `password`: kotlin.String): ImportResult {
            return FfiConverterTypeImportResult.lift(
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_import_xtream(
        FfiConverterString.lower(`name`),FfiConverterString.lower(`serverUrl`),FfiConverterString.lower(`username`),FfiConverterString.lower(`password`),_status)
}
    )
    }
    

    @Throws(OpenTiviException::class) fun `initEngine`(`dataDir`: kotlin.String): kotlin.UShort {
            return FfiConverterUShort.lift(
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_init_engine(
        FfiConverterString.lower(`dataDir`),_status)
}
    )
    }
    

    @Throws(OpenTiviException::class) fun `listChannels`(`sourceId`: kotlin.Long?, `groupName`: kotlin.String?, `search`: kotlin.String?, `favoritesOnly`: kotlin.Boolean?, `limit`: kotlin.UInt, `offset`: kotlin.UInt): List<ChannelInfo> {
            return FfiConverterSequenceTypeChannelInfo.lift(
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_list_channels(
        FfiConverterOptionalLong.lower(`sourceId`),FfiConverterOptionalString.lower(`groupName`),FfiConverterOptionalString.lower(`search`),FfiConverterOptionalBoolean.lower(`favoritesOnly`),FfiConverterUInt.lower(`limit`),FfiConverterUInt.lower(`offset`),_status)
}
    )
    }
    

    @Throws(OpenTiviException::class) fun `listFavorites`(): List<ChannelInfo> {
            return FfiConverterSequenceTypeChannelInfo.lift(
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_list_favorites(
        _status)
}
    )
    }
    

    @Throws(OpenTiviException::class) fun `listGroups`(`sourceId`: kotlin.Long?): List<kotlin.String> {
            return FfiConverterSequenceString.lift(
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_list_groups(
        FfiConverterOptionalLong.lower(`sourceId`),_status)
}
    )
    }
    

    @Throws(OpenTiviException::class) fun `listPlaybackCandidates`(`channelId`: kotlin.Long): List<PlaybackInfo> {
            return FfiConverterSequenceTypePlaybackInfo.lift(
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_list_playback_candidates(
        FfiConverterLong.lower(`channelId`),_status)
}
    )
    }
    

    @Throws(OpenTiviException::class) fun `listRecents`(): List<RecentChannelInfo> {
            return FfiConverterSequenceTypeRecentChannelInfo.lift(
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_list_recents(
        _status)
}
    )
    }
    

    @Throws(OpenTiviException::class) fun `listSources`(): List<SourceInfo> {
            return FfiConverterSequenceTypeSourceInfo.lift(
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_list_sources(
        _status)
}
    )
    }
    

    @Throws(OpenTiviException::class) fun `markRecentWatched`(`channelId`: kotlin.Long)
        = 
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_mark_recent_watched(
        FfiConverterLong.lower(`channelId`),_status)
}
    
    

    @Throws(OpenTiviException::class) fun `refreshSource`(`sourceId`: kotlin.Long): ImportResult {
            return FfiConverterTypeImportResult.lift(
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_refresh_source(
        FfiConverterLong.lower(`sourceId`),_status)
}
    )
    }
    

    @Throws(OpenTiviException::class) fun `resolvePlayback`(`channelId`: kotlin.Long): PlaybackInfo {
            return FfiConverterTypePlaybackInfo.lift(
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_resolve_playback(
        FfiConverterLong.lower(`channelId`),_status)
}
    )
    }
    

    @Throws(OpenTiviException::class) fun `searchEpg`(`search`: kotlin.String?, `state`: kotlin.String?, `limit`: kotlin.UInt?): List<EpgSearchResult> {
            return FfiConverterSequenceTypeEpgSearchResult.lift(
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_search_epg(
        FfiConverterOptionalString.lower(`search`),FfiConverterOptionalString.lower(`state`),FfiConverterOptionalUInt.lower(`limit`),_status)
}
    )
    }
    

    @Throws(OpenTiviException::class) fun `setFavorite`(`channelId`: kotlin.Long, `favorite`: kotlin.Boolean)
        = 
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_set_favorite(
        FfiConverterLong.lower(`channelId`),FfiConverterBoolean.lower(`favorite`),_status)
}
    
    

    @Throws(OpenTiviException::class) fun `setSetting`(`key`: kotlin.String, `value`: kotlin.String)
        = 
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_set_setting(
        FfiConverterString.lower(`key`),FfiConverterString.lower(`value`),_status)
}
    
    

    @Throws(OpenTiviException::class) fun `updateSource`(`sourceId`: kotlin.Long, `name`: kotlin.String, `location`: kotlin.String, `username`: kotlin.String?, `password`: kotlin.String?, `autoRefreshMinutes`: kotlin.UInt?, `enabled`: kotlin.Boolean)
        = 
    uniffiRustCallWithError(OpenTiviException) { _status ->
    UniffiLib.INSTANCE.uniffi_opentivi_android_fn_func_update_source(
        FfiConverterLong.lower(`sourceId`),FfiConverterString.lower(`name`),FfiConverterString.lower(`location`),FfiConverterOptionalString.lower(`username`),FfiConverterOptionalString.lower(`password`),FfiConverterOptionalUInt.lower(`autoRefreshMinutes`),FfiConverterBoolean.lower(`enabled`),_status)
}

}

